problems = [
    ["入出力", "", ""],
    ["水圧", "https://atcoder.jp/contests/abc231/tasks/abc231_a", "入出力に慣れましょう"],
    //    ["XOR", "https://atcoder.jp/contests/abc213/tasks/abc213_a", "XORの演算子？"],
    ["とにかく高橋", "https://atcoder.jp/contests/abc269/tasks/abc269_a", "複数入力も慣れましょう"],
    ["文字列比較", "https://atcoder.jp/contests/abc217/tasks/abc217_a", "文字列も"],
    ["５つの変数", "https://atcoder.jp/contests/abc170/tasks/abc170_a", "リストを使ってみよう"],
    ["数列の合計", "https://atcoder.jp/contests/abc272/tasks/abc272_a", "数列とリスト"],

    ["条件分岐", "", ""],
    ["仲間外れ", "https://atcoder.jp/contests/abc075/tasks/abc075_a", "条件を整頓する"],
    ["本の読み方", "https://atcoder.jp/contests/abc168/tasks/abc168_a", "orを使わない方法も"],
    ["ハンマー", "https://atcoder.jp/contests/abc270/tasks/abc270_b", "落ち着いて場合分け"],
    ["Product Max", "https://atcoder.jp/contests/abc178/tasks/abc178_b", "ヒント: max()"],
    ["電源プラグ", "https://atcoder.jp/contests/abc139/tasks/abc139_b", "落ち着いて考える"],

    ["文字列", "", ""],
    ["coffee", "https://atcoder.jp/contests/abc160/tasks/abc160_a", "文字インデックス"],
    ["Rotate", "https://atcoder.jp/contests/abc197/tasks/abc197_a", "正しくスライスを使う"],
    ["Tiers", "https://atcoder.jp/contests/abc224/tasks/abc224_a", "endswith()の使い方"],
    ["弱い暗証番号", "https://atcoder.jp/contests/abc212/tasks/abc212_b", "ヒント: データとしてパスワードを作る"],
    ["レジ打ち", "https://atcoder.jp/contests/abc283/tasks/abc283_c", "メソッドを有効に使おう"],

    ["繰り返し", "", ""],
    ["倍数", "https://atcoder.jp/contests/abc220/tasks/abc220_a", "数学的考察でも解けます"],
    ["貯金箱", "https://atcoder.jp/contests/abc206/tasks/abc206_b", "シミュレーション"],
    ["落単", "https://atcoder.jp/contests/abc222/tasks/abc222_b", "リストの処理もくり返し"],
    ["預金", "https://atcoder.jp/contests/abc165/tasks/abc165_b", "浮動小数点数注意（ヒント:整数で計算）"],
    ["ボールの魔法", "https://atcoder.jp/contests/abc216/tasks/abc216_c", "実は簡単"],

    ["関数", "", ""],
    ["ReLU", "https://atcoder.jp/contests/abc183/tasks/abc183_a", "関数定義してみよう"],
    ["奇妙な関数", "https://atcoder.jp/contests/abc234/tasks/abc234_a", "関数を絶対に定義しよう"],
    ["再帰関数", "https://atcoder.jp/contests/abc273/tasks/abc273_a", "再帰関数を覚えよう"],
    ["桁数の範囲", "https://atcoder.jp/contests/abc083/tasks/abc083_b", "桁数を計算する関数を定義しよう"],
    ["Kaprekar", "https://atcoder.jp/contests/abc192/tasks/abc192_c", "関数を覚えよう"],

    ["リストと繰り返し", "", ""],
    ["木の実", "https://atcoder.jp/contests/abc204/tasks/abc204_b", "リストの良い問題"],
    ["内積", "https://atcoder.jp/contests/abc188/tasks/abc188_b", "ヒント: zipを使う"],
    ["重複の除去", "https://atcoder.jp/contests/abc191/tasks/abc191_b", "データサイエンス向け"],
    ["クイズの得点", "https://atcoder.jp/contests/abc184/tasks/abc184_b", "シミュレーション、データ処理"],
    ["踏み台", "https://atcoder.jp/contests/abc176/tasks/abc176_c", "TLE?"],
    //["トーナメント", "https://atcoder.jp/contests/abc188/tasks/abc188_c", "総合力、シミュレーション"],

    ["文字列総合", "", ""],
    ["ROT N", "https://atcoder.jp/contests/abc146/tasks/abc146_b", "シーザ暗号"],
    ["難読文字", "https://atcoder.jp/contests/abc192/tasks/abc192_b", "少し総合力を試そう"],
    ["Mongeness", "https://atcoder.jp/contests/abc224/tasks/abc224_b", "良い問題"],
    ["大嫌いな７", "https://atcoder.jp/contests/abc186/tasks/abc186_c", "ヒント: oct(x)"],
    ["選挙", "https://atcoder.jp/contests/abc231/tasks/abc231_b", "辞書かカウンタ"],

    ["計算量", "", ""],
    ["1-2-4", "https://atcoder.jp/contests/abc270/tasks/abc270_a", "2進数の表現を考えると"],
    ["差分の和⭐️", "https://atcoder.jp/contests/abc186/tasks/abc186_d", "ループを減らす"],
    ["差分の最小値", "https://atcoder.jp/contests/abc212/tasks/abc212_c", "TLEを避けるのは難しい"],
    ["POW", "https://atcoder.jp/contests/abc205/tasks/abc205_c", "TLEを避けるには？"],
    ["メモ化再帰", "https://atcoder.jp/contests/abc275/tasks/abc275_d", "再計算をしない"],

    ["全探索", "", ""],
    ["非負整数の組", "https://atcoder.jp/contests/abc214/tasks/abc214_b", "全探索"],
    ["仕事の割り当て", "https://atcoder.jp/contests/abc194/tasks/abc194_b", "全探索の良問"],
    ["回転と回文", "https://atcoder.jp/contests/abc286/tasks/abc286_c", "文字列、全探索"],
    ["三角形", "https://atcoder.jp/contests/abc224/tasks/abc224_c", "全探索、良問"],
    ["サブマスク", "https://atcoder.jp/contests/abc269/tasks/abc269_c", "ビット全探索"],


    ["ソート", "", ""],
    ["ブービー賞", "https://atcoder.jp/contests/abc213/tasks/abc213_b", "リストを使いこなせているか？"],
    ["2 番目に高い山", "https://atcoder.jp/contests/abc201/tasks/abc201_b", "ソートとタプル"],
    ["順列判定", "https://atcoder.jp/contests/abc205/tasks/abc205_b", "ソートを使う"],
    ["同姓同名", "https://atcoder.jp/contests/abc216/tasks/abc216_b", "２重ループで判定してもいいが、Setを使うと楽"],
    ["最大の偶数", "https://atcoder.jp/contests/abc272/tasks/abc272_c", "ソートを使う"],

    ["データ構造", "", ""],
    ["グリッドブロック", "https://atcoder.jp/contests/abc186/tasks/abc186_b", "2次元リスト入門"],
    ["数列を数える", "https://atcoder.jp/contests/abc226/tasks/abc226_b", "Setを使う"],
    ["サイクルヒット", "https://atcoder.jp/contests/abc211/tasks/abc211_b", "重複除去　Setを使うと楽"],
    ["アメーバ", "https://atcoder.jp/contests/abc205/tasks/abc205_c", "辞書を活用する"],
    ["map", "https://atcoder.jp/contests/abc275/tasks/abc275_d", "辞書？"],

    ["総合", "", ""],
    ["180度", "https://atcoder.jp/contests/abc202/tasks/abc202_b", "文字リスト結合"],
    ["ビンゴ", "https://atcoder.jp/contests/abc157/tasks/abc157_b", "コードをしっかり書く力も必要"],
    ["導火線", "https://atcoder.jp/contests/abc223/tasks/abc223_c", "問題をよく読んで頑張る系"],
    ["トーナメント", "https://atcoder.jp/contests/abc188/tasks/abc188_c", "トーナメント表を分析すると"],
    ["長数列", "https://atcoder.jp/contests/abc220/tasks/abc220_c", "TLEを避ける"],

    ["後期の予習(アルゴリズム)", "", ""],
    ["階段", "https://atcoder.jp/contests/abc277/tasks/abc277_c", "DFS"],
    ["BFS", "https://atcoder.jp/contests/abc272/tasks/abc272_d", "BFS"],
    ["DFS", "https://atcoder.jp/contests/abc269/tasks/abc269_d", "DFS"],
    ["ツアー", "https://atcoder.jp/contests/abc204/tasks/abc204_c", "深さ優先探索(dfs)"],
    ["Weak Takahashi", "https://atcoder.jp/contests/abc232/tasks/abc232_d", "これが噂のDPか"],

]

problems2 = [
    ["腕だめし", "", ""],

    ["平均血圧 ", "https://atcoder.jp/contests/abc211/tasks/abc211_a", "数式の通り計算する"],
    ["Not", "https://atcoder.jp/contests/abc178/tasks/abc178_a", "if文を使いましょう"],
    ["９月９日", "https://atcoder.jp/contests/abc073/tasks/abc073_a", "文字列でも数値しても"],
    ["アルファベット", "https://atcoder.jp/contests/abc171/tasks/abc171_a", "文字列メソッド(upper/lower)"],
    ["関数を作ろう", "https://atcoder.jp/contests/abc172/tasks/abc172_a", "関数 f(a)を定義してみよう"],
    ["５つの変数", "https://atcoder.jp/contests/abc170/tasks/abc170_a", "リストを使ってみよう"],
    ["等差", "https://atcoder.jp/contests/abc201/tasks/abc201_a", "ソートを利用してみましょう"],
    ["差分の和", "https://atcoder.jp/contests/abc186/tasks/abc186_d", "Numpyを使おう"],
    ["計算する", "", ""],

    ["ディスカウント", "https://atcoder.jp/contests/abc193/tasks/abc193_a", "整数と浮動小数点数の違い"],
    ["世紀", "https://atcoder.jp/contests/abc200/tasks/abc200_a", "計算式はぐぐる"],
    ["最大値", "https://atcoder.jp/contests/abc137/tasks/abc137_a", "ヒント: max 関数"],
    ["両面印刷", "https://atcoder.jp/contests/abc157/tasks/abc157_a", "切り上げ"],
    ["カードの和", "https://atcoder.jp/contests/abc207/tasks/abc207_a", "解き方いろいろ、ソート、組み合わせのmax, minを引く"],
    ["星集め", "https://atcoder.jp/contests/abc192/tasks/abc192_a", "式を立てるのが楽しい？"],
    ["マグニチュード", "https://atcoder.jp/contests/abc221/tasks/abc221_a", "累乗"],
    ["ビリヤード", "https://atcoder.jp/contests/abc183/tasks/abc183_b", "ちょっと計算が面倒"],
    ["秒針", "https://atcoder.jp/contests/abc168/tasks/abc168_c", "math 紙と鉛筆で落ち着いて"],

    ["条件分岐", "", ""],
    ["百円硬貨", "https://atcoder.jp/contests/abc223/tasks/abc223_a", "条件分岐"],
    ["ABC", "https://atcoder.jp/contests/abc214/tasks/abc214_a", "文法 elif"],
    ["服の選び方", "https://atcoder.jp/contests/abc181/tasks/abc181_a", "数式化できるか？"],
    ["アイスクリーム", "https://atcoder.jp/contests/abc194/tasks/abc194_a", "場合わけを慎重に"],
    ["キャベツ", "https://atcoder.jp/contests/abc210/tasks/abc210_a", "落ち着いて考える"],
    ["じゃんけん", "https://atcoder.jp/contests/abc204/tasks/abc204_a", "コードを書く力も大切"],
    ["オンとオフ", "https://atcoder.jp/contests/abc228/tasks/abc228_a", "落ち着いて考える"],


    ["文字連結", "https://atcoder.jp/contests/abc149/tasks/abc149_a", "文字列の連結"],
    ["４桁", "https://atcoder.jp/contests/abc222/tasks/abc222_a", "定番: ゼロ埋め"],

    ["書き間違え", "https://atcoder.jp/contests/abc111/tasks/abc111_a", "replaceをうまく使おう"],
    ["ドットドットドット", "https://atcoder.jp/contests/abc168/tasks/abc168_b", "部分文字列"],
    ["辞書順", "https://atcoder.jp/contests/abc152/tasks/abc152_b", "辞書順（文字列の比較）"],
    ["四捨五入", "https://atcoder.jp/contests/abc226/tasks/abc226_a", "単純にround()では解けません"],
    ["繰り返し", "", ""],
    ["10円スタンプ", "https://atcoder.jp/contests/abc233/tasks/abc233_a", "ループか式を考えるか"],
    ["貯金箱", "https://atcoder.jp/contests/abc206/tasks/abc206_b", "シミュレーション"],
    ["倍数", "https://atcoder.jp/contests/abc220/tasks/abc220_a", "全探索か数学的考察で解きます"],
    ["預金", "https://atcoder.jp/contests/abc165/tasks/abc165_b", "浮動小数点数注意（ヒント整数で計算）"],
    ["大嫌いな７", "https://atcoder.jp/contests/abc186/tasks/abc186_c", "ヒント: oct(x)"],

    ["関数", "", ""],
    ["ReLU", "https://atcoder.jp/contests/abc183/tasks/abc183_a", "関数定義しよう"],
    ["奇妙な関数", "https://atcoder.jp/contests/abc234/tasks/abc234_a", "関数を絶対に定義しよう"],
    ["K進法", "https://atcoder.jp/contests/abc220/tasks/abc220_b", "API or 自作関数"],
    ["桁数の和", "https://atcoder.jp/contests/abc187/tasks/abc187_a", "ヒント: 関数  S(n)を定義"],
    ["繰り上がり", "https://atcoder.jp/contests/abc229/tasks/abc229_b", "関数を作るとよいかも"],
    ["Kaprekar", "https://atcoder.jp/contests/abc192/tasks/abc192_c", "関数　"],
    ["キーエンス本社ビル", "https://atcoder.jp/contests/abc227/tasks/abc227_b", "全探索ですよ"],

    ["リスト", "", ""],
    ["落単", "https://atcoder.jp/contests/abc222/tasks/abc222_b", "リストの基本的な問題"],
    ["木の実", "https://atcoder.jp/contests/abc204/tasks/abc204_b", "リストの良い問題"],
    ["ジェットコースター", "https://atcoder.jp/contests/abc142/tasks/abc142_b", "フィルタ"],
    ["文字コード", "https://atcoder.jp/contests/abc218/tasks/abc218_b", "文字コード"],
    ["内積", "https://atcoder.jp/contests/abc188/tasks/abc188_b", "ヒント: zipを使う"],
    ["重複の除去", "https://atcoder.jp/contests/abc191/tasks/abc191_b", "データサイエンス向け"],
    ["坊主めくり", "https://atcoder.jp/contests/abc210/tasks/abc210_b", "シミュレーション　もしくは、S.index('1') "],

    ["リスト発展", "", ""],
    ["奇妙な文字列", "https://atcoder.jp/contests/abc072/tasks/abc072_b", "可変長の文字列処理（リスト入門 join）"],
    ["Visibility", "https://atcoder.jp/contests/abc197/tasks/abc197_b", "２次元リスト"],
    ["リスト応用", "", ""],
    ["ブービー賞", "https://atcoder.jp/contests/abc213/tasks/abc213_b", "リストを使いこなせているか？"],
    ["2 番目に高い山", "https://atcoder.jp/contests/abc201/tasks/abc201_b", "ソートとタプル"],
    ["順列判定", "https://atcoder.jp/contests/abc205/tasks/abc205_b", "ソートを使う"],
    ["文字列シフト", "https://atcoder.jp/contests/abc223/tasks/abc223_b", "辞書順ソートを学ぼう"],
    ["チーズ", "https://atcoder.jp/contests/abc229/tasks/abc229_c", "ソートを使う"],
    ["タイポ", "https://atcoder.jp/contests/abc221/tasks/abc221_b", "スワップと探索"],
    ["データ構造", "", ""],
    ["スイス式", "https://atcoder.jp/contests/abc222/tasks/abc222_c", "シミュレーションで解けます"],
    ["異なる文字列", "https://atcoder.jp/contests/abc225/tasks/abc225_a", "Setで数えてもいいです"],
    ["数列を数える", "https://atcoder.jp/contests/abc226/tasks/abc226_b", "Setを使う"],

    ["効率を考える", "", ""],
    ["総和", "https://atcoder.jp/contests/abc181/tasks/abc181_b", "等差数列の和"],
    ["ボールの魔法", "https://atcoder.jp/contests/abc216/tasks/abc216_c", "ICPC向けの練習問題か"],
    ["アルゴリズム", "", ""],
    ["武術家", "https://atcoder.jp/contests/abc226/tasks/abc226_c", "深さ優先探索(dfs)"],
    ["コンマ", "https://atcoder.jp/contests/abc195/tasks/abc195_c", "総合力！"],


    ["表せない", "https://atcoder.jp/contests/abc193/tasks/abc193_c", "あと２問！"],



    ["ビット計算", "", ""],

    ["DP", "", ""],
    ["？", "https://atcoder.jp/contests/abc271/tasks/abc271_d", "DP"],

]

