problems = [
    //腕試し
    ["入門編: 解説用", "", ""],
    ["水圧", "https://atcoder.jp/contests/abc231/tasks/abc231_a", "入出力に慣れましょう"],
    ["ディスカウント", "https://atcoder.jp/contests/abc193/tasks/abc193_a", "整数と浮動小数点数の違い"],
    ["行列式", "https://atcoder.jp/contests/abc184/tasks/abc184_a", "複数入力も慣れましょう"],
    ["文字連結", "https://atcoder.jp/contests/abc149/tasks/abc149_a", "文字列"],
    ["カードの和", "https://atcoder.jp/contests/abc207/tasks/abc207_a", "解き方いろいろ、リストでも"],

    ["入門編: 計算する", "", ""],
    ["平均血圧 ", "https://atcoder.jp/contests/abc211/tasks/abc211_a", "式の通り計算する"],
    ["世紀", "https://atcoder.jp/contests/abc200/tasks/abc200_a", "計算式を考えよう"],
    ["マグニチュード", "https://atcoder.jp/contests/abc221/tasks/abc221_a", "累乗"],
    ["最大値", "https://atcoder.jp/contests/abc137/tasks/abc137_a", "ヒント: max関数"],
    ["ビリヤード🌟", "https://atcoder.jp/contests/abc183/tasks/abc183_b", "難問"],
    // ["両面印刷", "https://atcoder.jp/contests/abc157/tasks/abc157_a", "切り上げ"],

    ["入門編: 条件分岐", "", ""],
    ["Not", "https://atcoder.jp/contests/abc178/tasks/abc178_a", "if文を使いましょう"],
    ["百円硬貨", "https://atcoder.jp/contests/abc223/tasks/abc223_a", "条件分岐"],
    ["仲間外れ", "https://atcoder.jp/contests/abc075/tasks/abc075_a", "ちょっと工夫"],
    ["本の読み方", "https://atcoder.jp/contests/abc168/tasks/abc168_a", "リストで場合わけ"],
    // ["Product Max", "https://atcoder.jp/contests/abc178/tasks/abc178_b", "結構面白いかも"],
    ["電源プラグ🌟🌟", "https://atcoder.jp/contests/abc139/tasks/abc139_b", "落ち着いて"],

    ["入門編: 繰り返し", "", ""],
    ["10円スタンプ", "https://atcoder.jp/contests/abc233/tasks/abc233_a", "ループか式を考えるか"],
    ["星集め", "https://atcoder.jp/contests/abc192/tasks/abc192_a", "式を立てるのが楽しい？"],
    ["貯金箱", "https://atcoder.jp/contests/abc206/tasks/abc206_b", "シミュレーション"],
    ["倍数", "https://atcoder.jp/contests/abc220/tasks/abc220_a", "全探索か数学的考察"],
    ["ボールの魔法🌟🌟", "https://atcoder.jp/contests/abc216/tasks/abc216_c", "頭の体操"],

    ["初級編: 文字列", "", ""],
    ["９月９日", "https://atcoder.jp/contests/abc073/tasks/abc073_a", "文字列でも数値しても"],
    ["文字列比較", "https://atcoder.jp/contests/abc217/tasks/abc217_a", "文字列も比較できます"],
    ["Rotate", "https://atcoder.jp/contests/abc197/tasks/abc197_a", "正しくスライスを使う"],
    ["クイズの得点🌟", "https://atcoder.jp/contests/abc184/tasks/abc184_b", "シミュレーション、データ処理"],
    ["ROT N🌟🌟", "https://atcoder.jp/contests/abc146/tasks/abc146_b", "有名問題: シーザ暗号"],

    // ["腕だめし", "", ""],
    // ["アルファベット", "https://atcoder.jp/contests/abc171/tasks/abc171_a", "文字列メソッド(upper/lower)"],

    ["初級編: リスト", "", ""],
    ["５つの変数", "https://atcoder.jp/contests/abc170/tasks/abc170_a", "リストを使ってみよう"],
    ["木の実", "https://atcoder.jp/contests/abc204/tasks/abc204_b", "リストの良い問題"],
    ["落単", "https://atcoder.jp/contests/abc222/tasks/abc222_b", "大学生になって怖いもの"],
    ["重複の除去🌟", "https://atcoder.jp/contests/abc191/tasks/abc191_b", "データサイエンス向け"],
    ["グリッドブロック🌟🌟", "https://atcoder.jp/contests/abc186/tasks/abc186_b", "2次元リスト入門"],

    ["初級編: データ構造", "", ""],
    ["奇妙な文字列", "https://atcoder.jp/contests/abc072/tasks/abc072_b", "可変長の文字列処理"],
    ["2番目に高い山", "https://atcoder.jp/contests/abc201/tasks/abc201_b", "ソートとタプル"],
    ["同姓同名", "https://atcoder.jp/contests/abc216/tasks/abc216_b", "Setか辞書を使う"],
    ["選挙", "https://atcoder.jp/contests/abc231/tasks/abc231_b", "辞書を使おう"],
    ["チーズ", "https://atcoder.jp/contests/abc229/tasks/abc229_c", "ソートを使う"],
    //["導火線", "https://atcoder.jp/contests/abc223/tasks/abc223_c", "問題をよく読んで頑張る系"],
    //["ABC", "https://atcoder.jp/contests/abc214/tasks/abc214_a", "文法 elif"],
    //["ジェットコースター", "https://atcoder.jp/contests/abc142/tasks/abc142_b", "フィルタ"],

    ["中級編(ここから始まります）", "", ""],
    ["非負整数の組", "https://atcoder.jp/contests/abc214/tasks/abc214_b", "全探索に挑戦"],
    ["差分の和", "https://atcoder.jp/contests/abc186/tasks/abc186_d", "ループの数を減らす"],
    ["POW", "https://atcoder.jp/contests/abc205/tasks/abc205_c", "嫌らしい"],
    ["差分の最小値🌟", "https://atcoder.jp/contests/abc212/tasks/abc212_c", "TLEを避けよう"],
    ["ツアー🌟🌟", "https://atcoder.jp/contests/abc204/tasks/abc204_c", "深さ優先探索(dfs)"],

    ["動的計画法(DP)", "", ""],
    ["かえる🐸", "https://atcoder.jp/contests/dp/tasks/dp_a", "DP入門"],
    ["かえる🐸🐸", "https://atcoder.jp/contests/dp/tasks/dp_b", "これは解きたい"],
    ["夏休み", "https://atcoder.jp/contests/dp/tasks/dp_c", "夏休みはどうだった？"],
    ["ナップサック問題", "https://atcoder.jp/contests/dp/tasks/dp_d", "有名問題"],
    ["弱っちい高橋くん", "https://atcoder.jp/contests/abc232/tasks/abc232_d", "高橋さんとは？"],

    // ["服の選び方", "https://atcoder.jp/contests/abc181/tasks/abc181_a", "数式化できるか？"],
    // ["アイスクリーム", "https://atcoder.jp/contests/abc194/tasks/abc194_a", "場合わけを慎重に"],
    // ["キャベツ", "https://atcoder.jp/contests/abc210/tasks/abc210_a", "落ち着いて考える"],
    // ["じゃんけん", "https://atcoder.jp/contests/abc204/tasks/abc204_a", "コードを書く力も大切"],
    // ["オンとオフ", "https://atcoder.jp/contests/abc228/tasks/abc228_a", "落ち着いて考える"],

    // ["文字列", "", ""],
    // ["coffee", "https://atcoder.jp/contests/abc160/tasks/abc160_a", "文字インデックス"],
    // ["４桁", "https://atcoder.jp/contests/abc222/tasks/abc222_a", "定番: ゼロ埋め"],
    // ["Tiers", "https://atcoder.jp/contests/abc224/tasks/abc224_a", "endswith()の使い方"],
    // ["書き間違え", "https://atcoder.jp/contests/abc111/tasks/abc111_a", "replaceをうまく使おう"],
    // ["ドットドットドット", "https://atcoder.jp/contests/abc168/tasks/abc168_b", "部分文字列"],
    // ["辞書順", "https://atcoder.jp/contests/abc152/tasks/abc152_b", "辞書順（文字列の比較）"],
    // ["四捨五入", "https://atcoder.jp/contests/abc226/tasks/abc226_a", "単純にround()では解けません"],
    // ["ROT N", "https://atcoder.jp/contests/abc146/tasks/abc146_b", "有名問題: シーザ暗号"],
    // ["繰り返し", "", ""],
    // ["10円スタンプ", "https://atcoder.jp/contests/abc233/tasks/abc233_a", "ループか式を考えるか"],
    // ["貯金箱", "https://atcoder.jp/contests/abc206/tasks/abc206_b", "シミュレーション"],
    // ["倍数", "https://atcoder.jp/contests/abc220/tasks/abc220_a", "全探索か数学的考察で解きます"],
    // ["預金", "https://atcoder.jp/contests/abc165/tasks/abc165_b", "浮動小数点数注意（ヒント整数で計算）"],
    // ["難読文字", "https://atcoder.jp/contests/abc192/tasks/abc192_b", "少し総合力を試そう"],
    // ["仕事の割り当て", "https://atcoder.jp/contests/abc194/tasks/abc194_b", "全探索の良問"],
    // ["大嫌いな７", "https://atcoder.jp/contests/abc186/tasks/abc186_c", "ヒント: oct(x)"],
    // ["関数", "", ""],
    // ["ReLU", "https://atcoder.jp/contests/abc183/tasks/abc183_a", "関数定義しよう"],
    // ["奇妙な関数", "https://atcoder.jp/contests/abc234/tasks/abc234_a", "関数を絶対に定義しよう"],
    // ["K進法", "https://atcoder.jp/contests/abc220/tasks/abc220_b", "API or 自作関数"],
    // ["桁数の和", "https://atcoder.jp/contests/abc187/tasks/abc187_a", "ヒント: 関数  S(n)を定義"],
    // ["桁数の範囲", "https://atcoder.jp/contests/abc083/tasks/abc083_b", "ヒント: 桁数を計算する関数"],
    // ["繰り上がり", "https://atcoder.jp/contests/abc229/tasks/abc229_b", "関数を作るとよいかも"],
    // ["Kaprekar", "https://atcoder.jp/contests/abc192/tasks/abc192_c", "関数　"],
    // ["キーエンス本社ビル", "https://atcoder.jp/contests/abc227/tasks/abc227_b", "全探索ですよ"],
    // ["リスト", "", ""],
    // ["文字コード", "https://atcoder.jp/contests/abc218/tasks/abc218_b", "文字コード"],
    // ["内積", "https://atcoder.jp/contests/abc188/tasks/abc188_b", "ヒント: zipを使う"],
    // ["坊主めくり", "https://atcoder.jp/contests/abc210/tasks/abc210_b", "シミュレーション　もしくは、S.index('1') "],
    // ["トーナメント", "https://atcoder.jp/contests/abc188/tasks/abc188_c", "総合力、シミュレーション"],
    // ["リスト発展", "", ""],
    // ["180度", "https://atcoder.jp/contests/abc202/tasks/abc202_b", "文字リスト結合"],
    // ["Mongenessって何", "https://atcoder.jp/contests/abc224/tasks/abc224_b", "良い問題"],
    // ["ビンゴ", "https://atcoder.jp/contests/abc157/tasks/abc157_b", "コードをしっかり書く力も必要"],
    // ["弱い暗証番号", "https://atcoder.jp/contests/abc212/tasks/abc212_b", "ヒント: データとしてパスワードを作る"],
    // ["Visibility", "https://atcoder.jp/contests/abc197/tasks/abc197_b", "２次元リスト"],
    // ["三角形", "https://atcoder.jp/contests/abc224/tasks/abc224_c", "全探索、良問"],
    // ["リスト応用", "", ""],
    // ["順列判定", "https://atcoder.jp/contests/abc205/tasks/abc205_b", "ソートを使う"],
    // ["ブービー賞", "https://atcoder.jp/contests/abc213/tasks/abc213_b", "リストを使いこなせているか？"],
    // ["文字列シフト", "https://atcoder.jp/contests/abc223/tasks/abc223_b", "辞書順ソートを学ぼう"],
    // ["タイポ", "https://atcoder.jp/contests/abc221/tasks/abc221_b", "スワップと探索"],
    // ["データ構造", "", ""],
    // ["スイス式", "https://atcoder.jp/contests/abc222/tasks/abc222_c", "シミュレーションで解けます"],
    // ["サイクルヒット", "https://atcoder.jp/contests/abc211/tasks/abc211_b", "（解説）重複除去　Setを使うと楽"],
    // ["異なる文字列", "https://atcoder.jp/contests/abc225/tasks/abc225_a", "Setで数えてもいいです"],
    // ["数列を数える", "https://atcoder.jp/contests/abc226/tasks/abc226_b", "Setを使う"],
    // ["効率を考える", "", ""],
    // ["POW", "https://atcoder.jp/contests/abc205/tasks/abc205_c", "ヒント: Cが奇数かどうか"],
    // ["総和", "https://atcoder.jp/contests/abc181/tasks/abc181_b", "等差数列の和"],
    // ["差分の最小値", "https://atcoder.jp/contests/abc212/tasks/abc212_c", "TLEを避けるのは難しい"],
    // ["踏み台", "https://atcoder.jp/contests/abc176/tasks/abc176_c", "TLE?"],
    // ["長数列", "https://atcoder.jp/contests/abc220/tasks/abc220_c", "TLEを避ける"],
    // ["アルゴリズム", "", ""],
    // ["ツアー", "https://atcoder.jp/contests/abc204/tasks/abc204_c", "深さ優先探索(dfs)"],
    // ["武術家", "https://atcoder.jp/contests/abc226/tasks/abc226_c", "深さ優先探索(dfs)"],
    // ["コンマ", "https://atcoder.jp/contests/abc195/tasks/abc195_c", "総合力！"],
    // ["表せない", "https://atcoder.jp/contests/abc193/tasks/abc193_c", "あと２問！"],
]

